// <auto-generated />
using System;
using CentralBankRates.Server.db;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CentralBankRates.Server.Migrations
{
    [DbContext(typeof(CentralBankRatesContext))]
    partial class CentralBankRatesContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CentralBankRates.Server.db.CurrenciesCatalog", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("id");

                    b.Property<int>("Denomination")
                        .HasColumnType("int")
                        .HasColumnName("denomination");

                    b.Property<string>("EngName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("eng_name");

                    b.Property<string>("IsoCharCode")
                        .IsRequired()
                        .HasMaxLength(4)
                        .IsUnicode(false)
                        .HasColumnType("varchar(4)")
                        .HasColumnName("iso_char_code");

                    b.Property<int>("IsoNumCode")
                        .HasColumnType("int")
                        .HasColumnName("iso_num_code");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("name");

                    b.Property<string>("ParentCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("parent_code");

                    b.HasKey("Id")
                        .HasName("currencies_catalog_pk");

                    b.HasIndex(new[] { "IsoCharCode" }, "currencies_catalog_iso_char_code");

                    b.ToTable("currencies_catalog", (string)null);
                });

            modelBuilder.Entity("CentralBankRates.Server.db.RateOnDate", b =>
                {
                    b.Property<DateOnly>("Date")
                        .HasColumnType("date")
                        .HasColumnName("date");

                    b.Property<string>("CurrencyId")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("currencyId");

                    b.Property<double?>("Rate")
                        .HasColumnType("float")
                        .HasColumnName("rate");

                    b.HasKey("Date", "CurrencyId")
                        .HasName("rate_on_date_pk");

                    b.ToTable("rate_on_date", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
